media:
  input: static
  output: ""
content:
  - name: content
    label: Content
    type: collection
    path: 'content'
    view:
      fields: [ title, description, image ]
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: image
        label: image
        type: image
      - name: body
        label: Body
        type: rich-text
  